# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-10 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('body', models.TextField(verbose_name='文章主体内容，用Markdown编写')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, help_text='修改时间可以为空', null=True, verbose_name='修改时间')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞')),
                ('views', models.IntegerField(default=0, verbose_name='阅读数')),
                ('excerpt', models.CharField(blank=True, help_text='内容摘要，240字内，如果不填写则默认取前240个字', max_length=240, verbose_name='摘要')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SEO 优化', max_length=20, verbose_name='文章关键字')),
            ],
            options={
                'verbose_name_plural': '文章关键字',
                'verbose_name': '文章关键字',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户名')),
                ('text', models.TextField(verbose_name='内容')),
                ('create_date', models.DateTimeField(verbose_name='时间')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论的文章')),
            ],
            options={
                'verbose_name_plural': '评论',
                'ordering': ['-create_date'],
                'verbose_name': '评论',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='articlekeywd',
            field=models.ManyToManyField(help_text='选择一个或多个文章关键字', to='blog.ArticleKeyWords', verbose_name='关联文章关键字'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章作者'),
        ),
    ]
