# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(null=True),
        ),
    ]
