# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-08 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180806_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SEO 优化', max_length=20, verbose_name='文章关键字')),
            ],
            options={
                'verbose_name': '文章关键字',
                'verbose_name_plural': '文章关键字',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, help_text='内容摘要，240字内', max_length=240, verbose_name='摘要'),
        ),
    ]
