# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180808_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articlekeywd',
            field=models.ManyToManyField(help_text='选择一个或多个文章关键字', to='blog.ArticleKeyWords', verbose_name='关联文章关键字'),
        ),
    ]
