# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='侧边导航栏')),
                ('body', models.TextField(help_text='支持 Markdown 语法', verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '关于我们',
                'verbose_name': '关于我们',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=255, verbose_name='背景图')),
                ('create_time', models.DateTimeField(help_text='显示最新创建的图片', verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '首页关于我们简介背景图',
                'verbose_name': '首页关于我们简介背景图',
            },
        ),
        migrations.CreateModel(
            name='BootTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
            ],
            options={
                'verbose_name_plural': '底部导航栏标题',
                'verbose_name': '底部导航栏标题',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='编号决定图片播放顺序,少于三个', unique=True, verbose_name='编号')),
                ('title', models.CharField(blank=True, help_text='标题可以为空', max_length=20, null=True, verbose_name='标题')),
                ('img_url', models.CharField(max_length=255, verbose_name='图片地址')),
            ],
            options={
                'verbose_name_plural': '图片轮播',
                'ordering': ['id'],
                'verbose_name': '图片轮播',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
            ],
            options={
                'verbose_name_plural': '产品分类',
                'verbose_name': '产品分类',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywd', models.CharField(help_text='产品关键词，提供 SEO 优化', max_length=20, verbose_name='关键词')),
            ],
            options={
                'verbose_name_plural': '产品关键词',
                'ordering': ['keywd'],
                'verbose_name': '产品关键词',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=64, verbose_name='花名')),
                ('detail', models.TextField(help_text='150字以内的产品描述', max_length=150, verbose_name='简要描述')),
                ('price', models.FloatField(verbose_name='价格')),
                ('img_link', models.CharField(default='flower/images/flower-1.jpg', max_length=255, verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Category', verbose_name='产品分类')),
                ('keywords', models.ManyToManyField(help_text='关键词用来作为SEO中的keywords，数量为3-4个', to='flower.KeyWords', verbose_name='关键词')),
            ],
            options={
                'verbose_name_plural': '产品',
                'ordering': ['-create_time'],
                'verbose_name': '产品',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('description', models.CharField(blank=True, help_text='20字以内的描述', max_length=20, null=True, verbose_name='描述')),
                ('img_link', models.CharField(max_length=255, verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '终端形象（图片）',
                'ordering': ['-create_time'],
                'verbose_name': '终端形象（图片）',
            },
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='btTag',
            field=models.ForeignKey(help_text='与网页底部导航栏关联，可以在底部导航栏跳转到关于我们的页面', on_delete=django.db.models.deletion.CASCADE, to='flower.BootTag', verbose_name='关联的底部导航栏'),
        ),
    ]
