# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='侧边导航兰')),
                ('body', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywd', models.CharField(help_text='产品关键词，提供 SEO 优化', max_length=20, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '产品关键词',
                'verbose_name_plural': '产品关键词',
                'ordering': ['keywd'],
            },
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
