# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_auto_20180806_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='编号决定图片播放顺序,少于三个', unique=True, verbose_name='编号')),
                ('title', models.CharField(blank=True, help_text='标题可以为空', max_length=20, null=True, verbose_name='标题')),
                ('img_url', models.CharField(max_length=255, verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '图片轮播',
                'verbose_name_plural': '图片轮播',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=64, verbose_name='花名')),
                ('detail', models.TextField(help_text='150字以内的产品描述', verbose_name='简要描述')),
                ('price', models.FloatField(verbose_name='价格')),
                ('img_link', models.CharField(default='flower/images/flower-1.jpg', max_length=255, verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.Category', verbose_name='产品分类')),
                ('keywords', models.ManyToManyField(help_text='关键词用来作为SEO中的keywords，数量为3-4个', to='flower.KeyWords', verbose_name='关键词')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('description', models.CharField(blank=True, help_text='20字以内的描述', max_length=20, null=True, verbose_name='描述')),
                ('img_link', models.CharField(max_length=255, verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '终端形象（图片）',
                'verbose_name_plural': '终端形象（图片）',
                'ordering': ['-create_time'],
            },
        ),
    ]
