# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_carousel_category_product_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(help_text='150字以内的产品描述', max_length=150, verbose_name='简要描述'),
        ),
    ]
