# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_auto_20180806_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
            ],
            options={
                'verbose_name': '底部导航栏标题',
                'verbose_name_plural': '底部导航栏标题',
            },
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='boot_Tag',
            field=models.ForeignKey(help_text='与网页底部导航栏关联，可以在底部导航栏跳转到关于我们的页面', null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.BootTag', verbose_name='关联的底部导航栏'),
        ),
    ]
