# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_auto_20180807_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusmodel',
            old_name='boot_Tag',
            new_name='btTag',
        ),
    ]
