# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0006_auto_20180807_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='title',
            field=models.CharField(max_length=64, verbose_name='侧边导航栏'),
        ),
    ]
